[package]
name = "stream_depletion"
version = "0.1.0"
edition = "2024"

[dependencies]
scirs2-special = "0.1.0-alpha.1"
chrono = "0.4.41"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }